fix yaml para sonar project status api

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -41,21 +41,21 @@ jobs:
       - name: Check Quality Gate
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-          run: |
-            QG_STATUS=""
-            ATTEMPTS=0
-            while [ "$QG_STATUS" != "OK" ] && [ "$QG_STATUS" != "ERROR" ] && [ "$ATTEMPTS" -lt 10 ]; do
-              sleep 5
-              RESPONSE=$(curl -u $SONAR_TOKEN: https://sonarcloud.io/api/qualitygates/project_status?projectKey=${SONAR_PROJECT_KEY})
-              echo "Response: $RESPONSE"
-              QG_STATUS=$(echo $RESPONSE | jq -r .projectStatus.status)
-              if [ "$QG_STATUS" = "ERROR" ]; then
-                echo "Quality Gate check failed"
-                exit 1
-              fi
-              ATTEMPTS=$((ATTEMPTS + 1))
-            done
-            if [ "$QG_STATUS" != "OK" ]; then
-              echo "Quality Gate did not pass"
+        run: |
+          QG_STATUS=""
+          ATTEMPTS=0
+          while [ "$QG_STATUS" != "OK" ] && [ "$QG_STATUS" != "ERROR" ] && [ "$ATTEMPTS" -lt 10 ]; do
+            sleep 5
+            RESPONSE=$(curl -u $SONAR_TOKEN: https://sonarcloud.io/api/qualitygates/project_status?projectKey=${SONAR_PROJECT_KEY})
+            echo "Response: $RESPONSE"
+            QG_STATUS=$(echo $RESPONSE | jq -r .projectStatus.status)
+            if [ "$QG_STATUS" = "ERROR" ]; then
+              echo "Quality Gate check failed"
               exit 1
             fi
+            ATTEMPTS=$((ATTEMPTS + 1))
+          done
+          if [ "$QG_STATUS" != "OK" ]; then
+            echo "Quality Gate did not pass"
+            exit 1
+          fi
